site_name: SINETStream
nav:
  - Home: README.md
  - 'ユーザマニュアル': userguide/index.md
  - 'チュートリアル': tutorial/README.md
theme:
  name: readthedocs
  include_sidebar: false

extra_css:
  - "css/numbered.css"
