FROM debian:bookworm-20240612

# Install Apache Kafka
ARG KAFKA_VERSION=3.8.1
ENV KAFKA_VERSION=$KAFKA_VERSION
ARG KAFKA_URL=https://downloads.apache.org/kafka/${KAFKA_VERSION}/kafka_2.13-${KAFKA_VERSION}.tgz
# ARG KAFKA_URL=https://ftp.jaist.ac.jp/pub/apache/kafka/${KAFKA_VERSION}/kafka_2.13-${KAFKA_VERSION}.tgz
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
      openjdk-17-jdk-headless \
      curl \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN curl -s ${KAFKA_URL} | tar xzf - -C /srv \
 && ln -sf /srv/kafka_2.13-${KAFKA_VERSION} /srv/kafka

# Install Eclipse Mosquitto
RUN apt-get update  \
 && apt-get -y install --no-install-recommends \
      mosquitto \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Install Python
ARG PYTHON_VERSION=3.11
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
     python${PYTHON_VERSION} python3-pip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
ARG PYTHON_BINDIR=/usr/bin
# note: if install Python manually, see the old commit.
# ARG PYTHON_BINDIR=/usr/local/bin

# Install openssh
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
      openssh-server \
      openssh-client \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && rm -f /etc/ssh/ssh_host_*

# intall tools
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
      sudo \
      vim \
      iproute2 \
      procps \
      ca-certificates \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Install Supervisor
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
      supervisor \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -m 0700 /var/run/supervisor
COPY supervisord.conf /etc/supervisor/supervisord.conf

# Add user
ARG USERNAME=user01
RUN useradd -m $USERNAME \
 && echo "${USERNAME}:${USERNAME}" | chpasswd \
 && echo "${USERNAME} ALL=(ALL) ALL" > /etc/sudoers.d/90-${USERNAME}

COPY init-debian.sh /usr/local/bin/init.sh
CMD ["/usr/local/bin/init.sh"]

RUN suffix="$(echo ${PYTHON_VERSION} | cut -d . -f 1-2)" \
 && update-alternatives --install /usr/bin/python3 python3 "${PYTHON_BINDIR}/python${suffix}" 10 \
 && update-alternatives --install /usr/bin/pip3 pip3 "${PYTHON_BINDIR}/pip${suffix}" 10 \
 && sed -i.bak -e '/^#!.*python3\./n;/^#!.*python3/s|python3|python3.9|' \
      /usr/bin/supervisord /usr/bin/supervisorctl

EXPOSE 9092 9093 1883 8883 8080
ENV ENABLE_BROKER=true ENABLE_SSHD=false ENABLE_SSL=true \
  GENERATE_CLIENT_CERTS=true SSL_CLIENT_AUTH=requested

WORKDIR /home/$USERNAME
