FROM debian:bullseye-20230227

# Install Apache Kafka
ARG KAFKA_VERSION=3.4.0
ENV KAFKA_VERSION $KAFKA_VERSION
ARG KAFKA_URL=https://downloads.apache.org/kafka/${KAFKA_VERSION}/kafka_2.13-${KAFKA_VERSION}.tgz
# ARG KAFKA_URL=https://ftp.jaist.ac.jp/pub/apache/kafka/${KAFKA_VERSION}/kafka_2.13-${KAFKA_VERSION}.tgz
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
      openjdk-11-jdk-headless \
      curl \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN curl -s ${KAFKA_URL} | tar xzf - -C /srv \
 && ln -sf /srv/kafka_2.13-${KAFKA_VERSION} /srv/kafka

# Install Eclipse Mosquitto
RUN apt-get update  \
 && apt-get -y install --no-install-recommends \
      mosquitto \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Install Python
ARG PYTHON_VERSION=3.10.10
# hadolint ignore=DL3003
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
     build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl llvm \
     libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
 && curl "https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz" | tar xzf - \
 && ( \
       cd "Python-${PYTHON_VERSION}" \
    && ./configure --enable-loadable-sqlite-extensions --enable-optimizations --enable-option-checking=fatal --enable-shared --with-lto --with-system-expat --without-ensurepip \
    && make -j "$(nproc)" \
    && make altinstall \
    && cd .. \
    && rm -r "Python-${PYTHON_VERSION}" \
    ) \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && ldconfig \
 && curl https://bootstrap.pypa.io/get-pip.py | "/usr/local/bin/python$(echo ${PYTHON_VERSION} | cut -d . -f 1-2)"

# Install openssh
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
      openssh-server \
      openssh-client \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && rm -f /etc/ssh/ssh_host_*

# intall tools
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
      sudo \
      vim \
      iproute2 \
      procps \
      ca-certificates \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Install Supervisor
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
      supervisor \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -m 0700 /var/run/supervisor
COPY supervisord.conf /etc/supervisor/supervisord.conf

# Add user
ARG USERNAME=user01
RUN useradd -m $USERNAME \
 && echo "${USERNAME}:${USERNAME}" | chpasswd \
 && echo "${USERNAME} ALL=(ALL) ALL" > /etc/sudoers.d/90-${USERNAME}

COPY init-debian.sh /usr/local/bin/init.sh
CMD ["/usr/local/bin/init.sh"]

RUN suffix="$(echo ${PYTHON_VERSION} | cut -d . -f 1-2)" \
 && update-alternatives --install /usr/bin/python3 python3 "/usr/local/bin/python${suffix}" 10 \
 && update-alternatives --install /usr/bin/pip3 pip3 "/usr/local/bin/pip${suffix}" 10 \
 && sed -i -e 's%#!/usr/bin/python3$%#!/usr/bin/python3.9%' \
      /usr/bin/supervisord /usr/bin/supervisorctl

EXPOSE 9092 9093 1883 8883 8080
ENV ENABLE_BROKER=true ENABLE_SSHD=false ENABLE_SSL=true \
  GENERATE_CLIENT_CERTS=true SSL_CLIENT_AUTH=requested

WORKDIR /home/$USERNAME
