FROM ubuntu:20.04

# for tzdata
ENV DEBIAN_FRONTEND=noninteractive

#RUN apt update && apt install -y python3 python3-pip && 
RUN apt update && apt install -y python3 python3-sklearn python3-pandas vim-nox
