all:
	../gradlew build
test:
	#LANG=ja_JP.UTF_8 ../gradlew build --no-daemon --info --console plain
	#LANG=C ../gradlew test --no-daemon --info --console plain
	../gradlew test --rerun-tasks --info --console plain
