include ../../Makefile.comm

# XXX: warning: overriding recipe for target `test'
test:
	-$(SETUP) test

# how to test:
# cd $topdir
# make testenv
#     apt update
#     apt install make
#     make install
#     cd plugins/compression/lz4
#     python3 setup.py test
