service-1:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092

service-2:
  type: mqtt
  brokers:
    - 192.168.2.105:1883

bad-service-1:
  type: kafka
  brokers:
    - 127.0.0.1:9999

bad-service-2:
  type: mqtt
  brokers:
    - 127.0.0.1:9999

tls-service-1:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9093
    - kafka1.dp1.nii.ac.jp:9093
    - kafka2.dp1.nii.ac.jp:9093
  tls:
     ca_certs: tests/cert/ca.pem
     check_hostname: off

tls-service-1-default:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9093
    - kafka1.dp1.nii.ac.jp:9093
    - kafka2.dp1.nii.ac.jp:9093
  tls: true

service-1-9093:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9093
    - kafka1.dp1.nii.ac.jp:9093
    - kafka2.dp1.nii.ac.jp:9093

service-1-text:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  value_type: text

service-1-image:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  value_type: image

service-2-text:
  type: mqtt
  brokers:
    - 192.168.2.105:1883
  value_type: text

service-2-image:
  type: mqtt
  brokers:
    - 192.168.2.105:1883
  value_type: image

tls-service-2-default:
  type: mqtt
  brokers:
    - 192.168.2.105:8883
  tls: true

tls-service-2:
  type: mqtt
  brokers:
    - 192.168.2.105:8883
  tls:
     ca_certs: tests/cert/ca.pem
     certfile: tests/cert/client0.crt
     keyfile: tests/cert/client0.key

service-2-8883:
  type: mqtt
  brokers:
    - 192.168.2.105:8883
