service-1:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092

service-1-list-brokers:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
  topic: mss-test-001

service-1-str-brokers:
  type: kafka
  brokers: kafka0.dp1.nii.ac.jp:9092
  topic: mss-test-001

service-1-no-broker:
  type: kafka

service-1-three-brokers:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  topic: mss-test-001

service-1-sasl-plain:
  type: kafka
  brokers:
    - kafka0:9099
    - kafka1:9099
    - kafka2:9099
  tls:
     ca_certs: tests/cert/ca.pem
     check_hostname: off
  security_protocol: SASL_SSL
  sasl_mechanism: PLAIN
  sasl_plain_username: alice
  sasl_plain_password: alice-secret

service-2:
  type: mqtt
  brokers:
    - 192.168.2.105:1883

service-2-list-brokers:
  type: mqtt
  brokers:
    - 192.168.2.105:1883
  topic: mss-test-001

service-2-str-brokers:
  type: mqtt
  brokers: 192.168.2.105:1883
  topic: mss-test-001

service-2-two-brokers:
  type: mqtt
  brokers:
    - 192.168.2.105:1883
    - 192.168.2.106:1883
  topic: mss-test-001

service-2-no-broker:
  type: mqtt
  topic: mss-test-001

bad-service-1:
  type: kafka
  brokers:
    - 127.0.0.1:9999

bad-service-2:
  type: mqtt
  brokers:
    - 127.0.0.1:9999

tls-service-1:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9093
    - kafka1.dp1.nii.ac.jp:9093
    - kafka2.dp1.nii.ac.jp:9093
  tls:
     ca_certs: tests/cert/ca.pem
     check_hostname: off

tls-service-1-default:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9093
    - kafka1.dp1.nii.ac.jp:9093
    - kafka2.dp1.nii.ac.jp:9093
  tls: true

service-1-9093:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9093
    - kafka1.dp1.nii.ac.jp:9093
    - kafka2.dp1.nii.ac.jp:9093

service-1-text:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  value_type: text

service-1-image:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  value_type: image

service-2-text:
  type: mqtt
  brokers:
    - 192.168.2.105:1883
  value_type: text

service-2-image:
  type: mqtt
  brokers:
    - 192.168.2.105:1883
  value_type: image

tls-service-2-default:
  type: mqtt
  brokers:
    - 192.168.2.105:8883
  tls: true

tls-service-2:
  type: mqtt
  brokers:
    - 192.168.2.105:8883
  tls:
     ca_certs: tests/cert/ca.pem
     certfile: tests/cert/client0.crt
     keyfile: tests/cert/client0.key

service-2-8883:
  type: mqtt
  brokers:
    - 192.168.2.105:8883

service-crypto-1:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  crypto:
    algorithm: AES
    key_length: 128
    mode: CBC
    padding: none
    key_derivation:
      algorithm: pbkdf2
      salt_bytes: 16
      iteration: 10000
    password:
      value: secret-000
  data_encryption: true

test-cbc:
    type: kafka
    brokers:
        - kafka0.dp1.nii.ac.jp:9092
    crypto:
        algorithm: AES
        mode: CBC
        padding: pkcs7
        key_derivation:
            algorithm: pbkdf2
        password: secret-000
    data_encryption: true

test-cfb:
    type: kafka
    brokers:
        - kafka0.dp1.nii.ac.jp:9092
    crypto:
        algorithm: AES
        mode: CFB
        key_derivation:
            algorithm: pbkdf2
        password: secret-000
    data_encryption: true

test-ofb:
    type: kafka
    brokers:
        - kafka0.dp1.nii.ac.jp:9092
    crypto:
        algorithm: AES
        mode: OFB
        key_derivation:
            algorithm: pbkdf2
        password: secret-000
    data_encryption: true

test-ctr:
    type: kafka
    brokers:
        - kafka0.dp1.nii.ac.jp:9092
    crypto:
        algorithm: AES
        mode: CTR
        key_derivation:
            algorithm: pbkdf2
        password: secret-000
    data_encryption: true

test-openpgp:
    type: kafka
    brokers:
        - kafka0.dp1.nii.ac.jp:9092
    crypto:
        algorithm: AES
        #mode: OPENPGP
        mode: OPENPGPCFB
        #padding: none
        key_derivation:
            algorithm: pbkdf2
        password: secret-000
    data_encryption: true

test-eax:
    type: kafka
    brokers:
        - kafka0.dp1.nii.ac.jp:9092
    crypto:
        algorithm: AES
        mode: EAX
        key_derivation:
            algorithm: pbkdf2
        password: secret-000
    data_encryption: true

test-gcm:
    type: kafka
    brokers:
        - kafka0.dp1.nii.ac.jp:9092
    crypto:
        algorithm: AES
        mode: GCM
        key_derivation:
            algorithm: pbkdf2
        password: secret-000
    data_encryption: true

local-kafka:
  type: kafka
  brokers:
    - localhost:9092

local-kafka-authn-plain:
  type: kafka
  brokers:
    - localhost:9099
  security_protocol: SASL_PLAINTEXT
  sasl_mechanism: PLAIN
  sasl_plain_username: alice
  sasl_plain_password: alice-secret

local-kafka-authn-scram:
  type: kafka
  brokers:
    - localhost:9099
  security_protocol: SASL_PLAINTEXT
  sasl_mechanism: SCRAM-SHA-512
  sasl_plain_username: alice
  sasl_plain_password: alice-secret

local-mqtt:
  type: mqtt
  brokers:
    - localhost:1883

local-mqtt-authn:
  type: mqtt
  brokers:
    - localhost:1883
  username_pw_set:
    username: alice
    password: alice-secret

service-1-topic:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  topic: mss-test-001
  
service-1-topic-list-one-item:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  topic:
    - mss-test-001

service-1-topic-list:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  topic:
    - mss-test-001
    - mss-test-002

service-1-topics:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  topics: mss-test-001
  
service-1-topics-list:
  type: kafka
  brokers:
    - kafka0.dp1.nii.ac.jp:9092
    - kafka1.dp1.nii.ac.jp:9092
    - kafka2.dp1.nii.ac.jp:9092
  topics:
    - mss-test-001
    - mss-test-002
